# Generated by Django 5.0.3 on 2024-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_order',
            name='unshipped',
            field=models.CharField(choices=[('Unshipped', 'Unshipped'), ('Shipped', 'Shipped')], max_length=50),
        ),
    ]
