# Generated by Django 5.0.3 on 2024-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_alter_amazon_order_unshipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sage_SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sage_sku', models.CharField(max_length=100)),
                ('amazon_sku', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
            ],
        ),
    ]
