# Generated by Django 5.0.3 on 2024-03-13 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_sage_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_order',
            name='sage_sku',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
