version: '3.9'

services:
  web:
    build: 
      context: ./danuema
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./danuema:/app
    ports:
      - 8000:8000
